theme: jekyll-theme-cayman
title: Mail Server Factory
description: "Run your mail server like the boss!"
lang: en
languages:
  - en
  - ru
  - be
  - zh
  - hi
  - fa
  - ar
  - ko
  - ja
  - sr
  - fr
  - de
  - es
  - pt
  - no
  - da
  - sv
  - is
  - bg
  - ro
  - hu
  - it
  - el
  - he
  - ka
  - kk
  - uz
  - tg
  - tr
default_lang: en

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules/"
  - "vendor/"
  - "*.gemspec"
  - "*.rb"