#!/usr/bin/env python3
"""
Script to fix Serbian translations to use only Cyrillic script
"""

import yaml
import re

# Mapping of common English/Latin phrases to Serbian Cyrillic
LATIN_TO_CYRILLIC_CORRECTIONS = {
    # Technical terms that are in English
    '25 Distributions': '25 дистрибуција',
    'Website': 'Веб сајт',
    'is maintained by': 'одржава',
    'Server Factory': 'Server Factory',  # Brand name - keep as-is
    'This page was generated by': 'Ову страницу је генерисао',
    'GitHub Pages': 'GitHub Pages',  # Brand name - keep as-is
    'Mail Server Factory logo': 'Mail Server Factory лого',
    'Mail Server Factory - Run your mail server like the boss!': 'Mail Server Factory - Покрените свој мејл сервер као шеф!',
    'Open Source • Free Forever • Community Supported': 'Отворени код • Бесплатно заувек • Подршка заједнице',
    'Application Layer': 'Апликациони слој',
    'Docker': 'Docker',  # Brand name
    'Gradle': 'Gradle',  # Brand name
    'Java': 'Java',  # Brand name
    'JSON Configuration': 'JSON конфигурација',
    'Kotlin': 'Kotlin',  # Brand name
    'SSH Protocol': 'SSH протокол',
    'Security First': 'Безбедност на првом месту',
    'Defense-in-depth security with enterprise-grade encryption and monitoring': 'Вишеслојна безбедност са енкрипцијом и мониторингом предузећа',
    'Scalable': 'Скалабилно',
    'Horizontal scaling with stateless design and optimized resource utilization': 'Хоризонтално скалирање са оптимизованим коришћењем ресурса',
    'Observable': 'Посматрљиво',
    'Complete observability with metrics, logging, and health monitoring': 'Потпуна посматрљивост са метрикама, логовањем и мониторингом здравља',
    'Maintainable': 'Одрживо',
    'Hot reloading configuration and automated testing ensure reliability': 'Аутоматско учитавање конфигурације и тестирање осигуравају поузданост',
    'Enterprise Benefits': 'Предности предузећа',
    'Built With Modern Tools': 'Направљено са модерним алатима',
    'AES-256-GCM Encryption': 'AES-256-GCM енкрипција',
    'Health Checks': 'Провере здравља',
    'Structured Logging': 'Структурисано логовање',
    'Alert Management': 'Управљање упозорењима',
    'Environment Configs': 'Конфигурације окружења',
    'Hot Reloading': 'Аутоматско учитавање',
    'Schema Validation': 'Валидација шеме',
    'Secrets Management': 'Управљање тајнама',
    'Session Management': 'Управљање сесијама',
    'PostgreSQL': 'PostgreSQL',  # Brand name
    'Postfix': 'Postfix',  # Brand name
    'Dovecot': 'Dovecot',  # Brand name
    'Rspamd': 'Rspamd',  # Brand name
    'Redis': 'Redis',  # Brand name
    'ClamAV': 'ClamAV',  # Brand name
    'Audit Logging': 'Логовање ревизије',
    'TLS 1.3 Enforcement': 'Примена TLS 1.3',
}

def load_yaml(file_path):
    """Load YAML file"""
    with open(file_path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

def save_yaml(file_path, data):
    """Save YAML file"""
    with open(file_path, 'w', encoding='utf-8') as f:
        yaml.dump(data, f, allow_unicode=True, default_flow_style=False, sort_keys=False)

def fix_serbian_translations(translations_file):
    """Fix Serbian translations to use only Cyrillic"""
    print(f"Loading {translations_file}...")
    translations = load_yaml(translations_file)

    if 'sr' not in translations:
        print("❌ Serbian (sr) language not found!")
        return

    sr_translations = translations['sr']
    fixed_count = 0

    print("\nFixing Serbian translations...")

    for key, value in sr_translations.items():
        if isinstance(value, str):
            original_value = value

            # Apply corrections
            for latin, cyrillic in LATIN_TO_CYRILLIC_CORRECTIONS.items():
                if latin in value:
                    value = value.replace(latin, cyrillic)

            # Update if changed
            if value != original_value:
                sr_translations[key] = value
                print(f"  Fixed '{key}':")
                print(f"    Before: {original_value}")
                print(f"    After:  {value}")
                fixed_count += 1

    # Update the translations
    translations['sr'] = sr_translations

    print(f"\n✅ Total fixes: {fixed_count}")
    print(f"Saving {translations_file}...")
    save_yaml(translations_file, translations)
    print("✅ Done!")

if __name__ == "__main__":
    translations_file = "../_data/translations.yml"
    fix_serbian_translations(translations_file)
